---
- name: Converge
  hosts: all
  tasks:
    # - name: Include ansible_burp2_server
    #   include_role:
    #     name: coffeeitworks.burp2_server
    - name: Include ansible_burpui_server
      include_role: 
        name: ansible_burpui_server
      tags:
        - burpui-server
