---

# - name: Upgrade sql requirements
#   pip:
#     name: burp-ui[sql]
#     state: 0.4.2

- name: bui-upgrade | Upgrade database schema
  shell: "LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 {{ burpui_virtualenv_bin }}/bui-manage -c /etc/burp/burpui.cfg db upgrade"
  ignore_errors: yes
  changed_when: False

# TODO: Change user to burpui
# TODO: check other way to run it without breaking ansible task
#- name: Upgrade celery beat
#  shell: bui-celery -c /etc/burp/burpui.cfg -- --beat
#  environment: 
#    C_FORCE_ROOT: "True"

# Restart services
- meta: flush_handlers
