---
# https://github.com/ziirish/burp-ui/blob/master/docs/gunicorn.rst

#- name: debug see vars
#  debug:
#    msg: "distribution: {{ ansible_distribution }}, major version: {{ ansible_distribution_major_version|int }}, pip exe: {{ python_pip_executable  }} "

- name: gunicorn | directory /var/log/gunicorn 
  file: 
    path: '/var/log/gunicorn'
    state: directory
    owner: "{{ burpui_user }}"
    group: "{{ burpui_group }}"

# use pip always for pip2 or pip3, for systemd or upstart
- name: gunicorn | Install gunicorn from pip
  pip:
    name: gunicorn>=19.7.1
    state: present
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"

- name: check "{{ burpui_virtualenv }}/gunicorn/bin/gunicorn" stat
  stat: 
    path: "{{ burpui_virtualenv_bin }}/gunicorn"
  register: gunicorn_local_bin_stat

- name: set "{{ burpui_virtualenv }}/gunicorn/bin/gunicorn" as gunicorn path
  set_fact:
    burpui_gunicorn_bin: "{{ burpui_virtualenv_bin }}/gunicorn"
  when: gunicorn_local_bin_stat.stat.exists

- block:

  - name: gunicorn | Debian configure gunicorn server
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "gunicorn_logrotate.j2", dest: "/etc/logrotate.d/gunicorn" }
    notify: restart burpui services
  
  when: ansible_os_family == 'Debian' and not gunicorn_systemd_service and not gunicorn_upstart_service

# This is for python2 or 3 gunicorn with systemd
- name: gunicorn | setup gunicorn.service systemd
  template:
    src: gunicorn_systemd.j2
    dest: /etc/systemd/system/gunicorn.service
    mode: 0755
    owner: root
    group: root
  when: ansible_os_family == 'RedHat' or gunicorn_systemd_service

- name: gunicorn | copy burpui_gunicorn.py file
  template:
    mode: 0755
    src: burpui_gunicorn.py.j2
    dest: /etc/burp/burpui_gunicorn.py
    owner: root
    group: root
  when: ansible_os_family == 'RedHat' or gunicorn_systemd_service or gunicorn_upstart_service

- name: gunicorn | setup gunicorn upstart service
  template:
    src: gunicorn_upstart.j2
    dest: /etc/init/gunicorn.conf
    mode: 0755
    owner: root
    group: root
  when: gunicorn_upstart_service
