---

- name: pip3 | install virtualenv from pip3
  pip:
    name: "virtualenv>=20.16.6"
    state: present
    executable: "pip3"

- name: pip3 | check only if burpui is installed
  pip:
    name: "{{ burpui_pip_burpui }}"
    state: present
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"
  register: burpui_installed_check
  check_mode: yes

- name: pip3 | update pip
  pip:
    name: 'pip>=20'
    state: present
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"

- name: pip3 | install pip packages
  pip:
    name: '{{ burpui_pip_present }}'
    state: present
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"
  when: not burpui_use_dev

- name: pip3 | install pip dev packages from requirements_dev.txt
  pip:
    requirements: "{{ burpui_virtualenv }}/requirements_dev.txt"
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"
  when: burpui_use_dev

- name: pip3 | Install pip packages by version
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"
  with_items: "{{ burpui_pip_packages }}"
  register: bui_pip_install
  when: not burpui_use_dev
  notify: restart burpui services

- name: pip3 | workaround link to /bin/flask
  ansible.builtin.file:
    src: "{{ burpui_virtualenv_bin }}/flask"
    dest: /bin/flask
    owner: root
    group: root
    mode: '0755'
    state: link
 
- name: pip3 | Install pip packages by tar.gz
  pip:
    name: "{{ burpui_pip_burpui_dev }}"
    state: present
    virtualenv: "{{ burpui_virtualenv }}"
    virtualenv_python: "{{ burpui_virtualenv_python }}"
  register: bui_pip_install
  when: burpui_use_dev
  notify: restart burpui services

- name: bui-celery | links to /usr/local/bin
  ansible.builtin.file:
    src: "{{ burpui_virtualenv_bin }}/{{ item }}"
    dest: "{{ burpui_local_bin }}/{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: link
  with_items: "{{ burpui_bin_links }}"
