---

- name: pip3 | check only if burpui is installed
  pip:
    name: "{{ burpui_pip_burpui }}"
    state: present
    executable: "{{ python3_pip }}"
  register: burpui_installed_check
  check_mode: yes

- name: pip3 | update pip
  pip:
    name: 'pip>=20'
    state: present
    executable: "{{ python3_pip }}"

- name: pip3 | install pip packages
  pip:
    name: '{{ burpui_pip_present }}'
    state: present
    executable: "{{ python3_pip }}"
  when: not burpui_use_dev

- name: pip3 | install pip dev packages
  pip:
    name: '{{ burpui_pip_dev_present }}'
    state: present
    executable: "{{ python3_pip }}"
  when: burpui_use_dev

- name: pip3 | Install pip packages by version
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version}}"
    executable: "{{ python3_pip }}"
  with_items: "{{ burpui_pip_packages }}"
  register: bui_pip_install
  when: not burpui_use_dev
  notify: restart burpui services
 
- name: pip3 | Install pip packages by tar.gz
  shell: "{{ python3_pip }} install -e {{ burpui_pip_burpui_dev }}"
  register: bui_pip_install
  when: burpui_use_dev
  notify: restart burpui services
  changed_when: false
