---
- name: Converge
  hosts: all
  vars:
    burpui_standalone: True
    burpui_use_dev: False
  tasks:
    - name: Include ansible_burpui_server
      include_role: 
        name: ansible_burpui_server
      tags:
        - burpui-server